# Generated by Django 5.0.6 on 2025-01-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_active_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='files',
            field=models.ManyToManyField(null=1, to='app.file', verbose_name='files'),
            preserve_default=1,
        ),
    ]
