# Generated by Django 5.0.6 on 2025-01-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_file_user_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.DeleteModel(
            name='admin',
        ),
    ]
