# Generated by Django 5.0.6 on 2025-01-23 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_admin_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='admins'),
        ),
    ]
