# Generated by Django 5.0.6 on 2025-01-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view', 'Can view'), ('can_change', 'Can change'))},
        ),
    ]
